const carFeatures = [
  ,
  "2 Zone Climate",
  "3 Zone Climate",
  "ACC Adaptive Cruise Control",
  "Access Pack",
  "Active Park Assist",
  "Adaptive LED Headlights",
  "Air Conditioning",
  "Air Scarf",
  "Air Suspension",
  "All Wheel Drive",
  "Alloy Wheels",
  "Ambient Air Package",
  "Ambient Lighting",
  "AMG body styling",
  "AMG Leather Steering Wheel",
  "AMG Night Pack",
  "AMG Performance Exhaust",
  "AMG Performance Suspension",
  "AMG Sport Pack",
  "Android Auto",
  "Appearance Pack",
  "Apple CarPlay",
  "Artico Leather",
  "Audi Advanced Key",
  "Audi Connect",
  "Audi Parking System",
  "Aux Input",
  "Bang & Olufsen Speakers",
  "Black Panel Display",
  "Blackline Specification",
  "Blind Spot Assist",
  "Bluetooth",
  "BMW Apps Interface",
  "BMW Gesture Control",
  "BMW Online",
  "Bose",
  "Brake Assist",
  "Brand New Sports Alloys & Tyres",
  "Burmester Speakers",
  "Business Navigation",
  "CD Player",
  "Central Locking",
  "Chili Pack",
  "City Pack",
  "Climate Control",
  "Cold Weather Pack",
  "Comand Sat Nav",
  "Comfort Access",
  "Comfort Pack",
  "Comfort Ventilated Front Seats",
  "Cooled Glovebox",
  "Cooled Seats",
  "Cruise Control",
  "DAB Radio",
  "Digital Cockpit",
  "DVD Player",
  "Dynamic Chassis Control",
  "Dynamic Pack",
  "Electric Rear Seats",
  "Electric Roof",
  "Electric Seats",
  "Electric Steering Wheel",
  "Electric Sunroof",
  "Electric Windows",
  "Executive Lounge Seating",
  "Flat Bottom Steering Wheel",
  "Ford SYNC",
  "Front centre armrest",
  "Front fog lights",
  "Full Leather",
  "Garmin Map Pilot",
  "Hard Drive Storage",
  "Harman Kardon Speakers",
  "Headlamp Jetwash",
  "Heads up Display",
  "Heated Rear Seats",
  "Heated Seats",
  "Heated Steering Wheel",
  "Heated Windscreen",
  "Hey Mercedes Voice Activation",
  "IDrive",
  "Intelligent Led Lights",
  "Internet",
  "Ipod Connectivity",
  "Isofix",
  "Key-less Entry",
  "Keyless Go",
  "Lane Assist",
  "LED daytime running lights",
  "Lumbar Support",
  "M Sport Bodykit",
  "M Sport Plus Pack",
  "M Sport Steering Wheel",
  "Massage Function Seats",
  "Media Pack Business",
  "Media Pack Business Advanced",
  "Media Pack Professional",
  "Memory Pack",
  "Memory Seats",
  "Mercedes Me",
  "Meridian Speakers",
  "MINI Connected",
  "MINI Sports Pack",
  "Mirror Pack",
  "MP3 Audio",
  "Multi Function Steering Wheel",
  "Multi-Contour Front Seats",
  "Paddle Shift",
  "Panoramic Roof",
  "Parking Camera",
  "Parking Pack",
  "Parking Sensors",
  "Part Leather",
  "Pepper Pack",
  "Power Steering",
  "Powered Folding Mirrors",
  "Premium",
  "Premium Plus",
  "Premium Sound System",
  "Privacy Glass",
  "Professional Nav",
  "Push Button Start",
  "Radio Visual Boost",
  "Rain Sensing Wipers",
  "Real Time Traffic Info",
  "Rear Entertainment",
  "Rear Entertainment System",
  "Rear Spoiler",
  "Rear Wiper",
  "Roof Rails",
  "Running Boards",
  "S Line Body Styling",
  "Salt Pack",
  "Sat Nav",
  "Sat Nav Ready (no SD card)",
  "Soft Close Doors",
  "Split Rear Seats",
  "Sport Exhaust",
  "Sports Pack",
  "Sports Seats",
  "ST Style Pack",
  "Start-Stop",
  "Storage Pack",
  "Sun Protection Pack",
  "Surround View",
  "Surround View Cameras",
  "Third Row Seats",
  "Touch Pad",
  "Touch Screen Control",
  "TV",
  "Update this",
  "USB Interface",
  "Variable Damper Control",
  "Virtual Cockpit",
  "Visibility Pack",
  "Voice Control",
  "Wi-Fi Hot Spot Prep",
  "Wireless Phone Charging",
  "Xenon Headlamps",
];
